// Auto-generated by add_indices.py
import ProblemView from "./ProblemView";
import ScoreView from "./ScoreView";
import VersionView from "./VersionView";

export { ProblemView, ScoreView, VersionView };
